version: "2"
run:
  concurrency: 6
linters:
  enable:
    - asciicheck
    - bodyclose
    - dogsled
    - errorlint
    - exhaustive
    - forbidigo
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - makezero
    - misspell
    - nakedret
    - nestif
    - noctx
    - predeclared
    - protogetter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - thelper
    - tparallel
    - unconvert
    - whitespace
    - wrapcheck
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    forbidigo:
      forbid:
        - pattern: ^print.*$
        - pattern: ^spew\.(ConfigState\.)?Dump$
        - pattern: ^spew.Dump$
          pkg: ^github.com/davecgh/go-spew/spew$
    gocritic:
      enabled-checks:
        - appendAssign
        - argOrder
        - badCond
        - caseOrder
        - codegenComment
        - commentedOutCode
        - deprecatedComment
        - dupArg
        - dupBranchBody
        - dupCase
        - dupSubExpr
        - exitAfterDefer
        - flagDeref
        - flagName
        - nilValReturn
        - offBy1
        - sloppyReassign
        - weakCond
        - octalLiteral
        - appendCombine
        - equalFold
        - hugeParam
        - indexAlloc
        - rangeExprCopy
        - rangeValCopy
        - captLocal
        - commentFormatting
        - commentedOutImport
        - defaultCaseOrder
        - docStub
        - elseif
        - emptyFallthrough
        - emptyStringTest
        - hexLiteral
        - ifElseChain
        - methodExprCall
        - regexpMust
        - singleCaseSwitch
        - sloppyLen
        - stringXbytes
        - switchTrue
        - typeAssertChain
        - typeSwitchVar
        - underef
        - unlabelStmt
        - unlambda
        - unslice
        - valSwap
        - wrapperFunc
        - yodaStyleExpr
    godox:
      keywords:
        - BUG
        - FIXME
        - HACK
    protogetter:
      skip-any-generated: true
    wrapcheck:
      ignore-package-globs:
        - google.golang.org/grpc/*
  exclusions:
    generated: lax
    presets:
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  new-from-rev: ""
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - Standard
        - Default
        - Prefix(web_clean_arch)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
