# https://taskfile.dev

version: '3'

vars:
  GOLINTER: $(go env GOPATH)/bin/golangci-lint

dotenv: ['.env']

tasks:
  default:
    cmds:
      -  echo "{{.CLI_ARGS}}"
    silent: true
  lint:
    cmds:
      -  $(go env GOPATH)/bin/golangci-lint run
    silent: true
  api:
    cmds:
      -  go run cmd/api/main.go
    silent: true
  cli:
    cmds:
      - go run cmd/cli/main.go  
    silent: true
